version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventify
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/eventify
      - JWT_SECRET=supersecretjwt
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_USER=your_ethereal_user
      - SMTP_PASS=your_ethereal_pass
      - APP_BASE_URL=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  dbdata:
